version: '3.7'
services:
    rrd-server:
        image: grafana-rrd
        build:
            context: ./grafana-rrd-server
        restart: unless-stopped
        ## activate this port for debugging only
        # ports:
        #    - 9000:9000
        environment:
            - RRD_STEP=600
        volumes:
            - ./rrd-data:/rrd-data

    grafana:
        image: grafana/grafana
        restart: unless-stopped
        ports:
            - 127.0.0.1:3000:3000
        environment:
            - GF_SERVER_ROOT_URL=http://grfn.localhost
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=changeme
            - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
            ## smtp-related settings
            - GF_SMTP_ENABLED=true
            # must give host _and_ port
            - GF_SMTP_HOST=mail.sample.org:587
            - GF_SMTP_FROM_ADDRESS=grafana@sample.org
            # mail credentials for the mail server
            - GF_SMTP_USER=bob
            - GF_SMTP_PASSWORD=changeme
            # analytics
            - GF_ANALYTICS_CHECK_FOR_UPDATES=true
            - GF_ANALYTICS_REPORTING_ENABLED=false
            # users
            - GF_USERS_ALLOW_ORG_CREATE=false
            - GF_USERS_ALLOW_SIGN_UP=false
            # log
            - GF_LOG_FILTERS=
            - GF_LOG_LEVEL=info
            - GF_LOG_MODE=console
            # log.console
            - GF_LOG_CONSOLE_FORMAT=console
            - GF_LOG_CONSOLE_LEVEL=info
            # auth.basic
            - GF_AUTH_BASIC_ENABLED=true
            # auth.anonymous
            - GF_AUTH_ANONYMOUS_ENABLED=false
            - GF_AUTH_ANONYMOUS_ORG_NAME="Main Org."
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
        volumes:
            - grafana:/var/lib/grafana

volumes:
    grafana:
